version: "2.3"

services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - .docker/.volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    restart: always
  app:
    build:
      context: .
      dockerfile: .docker/local.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: common.env
    command: python manage.py runserver 0.0.0.0:8086
    ports:
      - "8086:8086"
    depends_on:
      - db
  worker:
    build:
      context: .
      dockerfile: .docker/local.Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: common.env
    command: celery -A app worker -B --loglevel=info -Q celery,celery:1
    depends_on:
      - db
      - redis
